[font]
name = "sitelen seli kiwen juniko"
size = 20

[layout]
vertical = false

[color]
clip = "#0078D7"
background = "#FAFAFA"
highlight = "#E8E8FF"
index = "#A0A0A0"
candidate = "black"
highlighted = "black"

[behavior]
toggle = "Ctrl"
long_pi = false
long_glyph = false
