[font]
name = "sitelen seli kiwen juniko"
size = 20

[layout]
vertical = false

[color]
candidate = "#000000"
index = "#A0A0A0"
background = "#FAFAFA"
clip = "#0078D7"
highlight = "#E8E8FF"
highlighted = "#000000"

[behavior]
toggle = "Ctrl"
long_pi = false
long_glyph = false
cjk_space = false
